# -*- coding: utf-8 -*-
test_list = [
    {'name': 'Zechariah', 'chapters': 14, 'title': u'匝加利亞 Zechariah'}
]

new_testiment_book_list = [
    {'name': 'Matthew', 'chapters': 28, 'title': u'瑪竇福音 Matthew', 'sk_title': u'瑪竇福音', 'cu_title': u'馬太福音'},
    {'name': 'Mark', 'chapters': 16, 'title': u'馬爾谷福音 Mark', 'sk_title': u'馬爾谷福音', 'cu_title': u'馬可福音'},
    {'name': 'Luke', 'chapters': 24, 'title': u'路加福音 Luke', 'sk_title': u'路加福音', 'cu_title': u'路加福音'},
    {'name': 'John', 'chapters': 21, 'title': u'若望福音 John', 'sk_title': u'若望福音', 'cu_title': u'約翰福音'},
    {'name': 'Acts', 'chapters': 28, 'title': u'宗徒大事錄 Acts', 'sk_title': u'宗徒大事錄', 'cu_title': u'使徒行傳'},
    {'name': 'Romans', 'chapters': 16, 'title': u'羅馬書 Roman', 'sk_title': u'羅馬書', 'cu_title': u'羅馬書'},
    {'name': '1_Corinthians', 'chapters': 16, 'title': u'格林多前書 1 Corinthians', 'sk_title': u'格林多前書', 'cu_title': u'哥林多前書'},
    {'name': '2_Corinthians', 'chapters': 13, 'title': u'格林多後書 2 Corinthians', 'sk_title': u'格林多後書', 'cu_title': u'哥林多後書'},
    {'name': 'Galatians', 'chapters': 6, 'title': u'迦拉達書 Galatians', 'sk_title': u'迦拉達書', 'cu_title': u'加拉太書'},
    {'name': 'Ephesians', 'chapters': 6, 'title': u'厄弗所書 Ephesians', 'sk_title': u'厄弗所書', 'cu_title': u'以弗所書'},
    {'name': 'Philippians', 'chapters': 4, 'title': u'斐理伯書 Philippians', 'sk_title': u'斐理伯書', 'cu_title': u'腓利比書'},
    {'name': 'Colossians', 'chapters': 4, 'title': u'哥羅森書 Colossians', 'sk_title': u'哥羅森書', 'cu_title': u'歌羅西書'},
    {'name': '1_Thessalonians', 'chapters': 5, 'title': u'得撒洛尼前書 1 Thessalonians', 'sk_title': u'得撒洛尼前書', 'cu_title': u'帖撒羅尼迦前書'},
    {'name': '2_Thessalonians', 'chapters': 3, 'title': u'得撒洛尼後書 2 Thessalonians', 'sk_title': u'得撒洛尼後書', 'cu_title': u'帖撒羅尼迦後書'},
    {'name': '1_Timothy', 'chapters': 6, 'title': u'弟茂德前書 1Timothy', 'sk_title': u'弟茂德前書', 'cu_title': u'提摩太前書'},
    {'name': '2_Timothy', 'chapters': 4, 'title': u'弟茂德後書 2Timothy', 'sk_title': u'弟茂德後書', 'cu_title': u'提摩太後書'},
    {'name': 'Titus', 'chapters': 2, 'title': u'弟鐸書 Titus', 'sk_title': u'弟鐸書', 'cu_title': u'提多書'},
    {'name': 'Philemon', 'chapters': 1, 'title': u'費肋孟書 Philemon', 'sk_title': u'費肋孟書', 'cu_title': u'腓利門書'},
    {'name': 'Hebrews', 'chapters': 13, 'title': u'希伯來書 Hebrews', 'sk_title': u'希伯來書', 'cu_title': u'希伯來書'},
    {'name': 'James', 'chapters': 5, 'title': u'雅各伯書 James', 'sk_title': u'雅各伯書', 'cu_title': u'雅各書'},
    {'name': '1_Peter', 'chapters': 5, 'title': u'伯多祿前書 1 Peter', 'sk_title': u'伯多祿前書', 'cu_title': u'彼得前書'},
    {'name': '2_Peter', 'chapters': 3, 'title': u'伯多祿後書 2 Peter', 'sk_title': u'伯多祿後書', 'cu_title': u'彼得後書'},
    {'name': '1_John', 'chapters': 5, 'title': u'若望一書 1 John', 'sk_title': u'若望一書', 'cu_title': u'約翰壹書'},
    {'name': '2_John', 'chapters': 1, 'title': u'若望二書 2 John', 'sk_title': u'若望二書', 'cu_title': u'約翰貳書'},
    {'name': '3_John', 'chapters': 1, 'title': u'若望三書 3 John', 'sk_title': u'若望三書', 'cu_title': u'約翰參書'},
    {'name': 'Jude', 'chapters': 1, 'title': u'猶達書 Jude', 'sk_title': u'猶達書', 'cu_title': u'猶大書'},
    {'name': 'Revelation', 'chapters': 22, 'title': u'若望默示錄  Revelation', 'sk_title': u'若望默示錄', 'cu_title': u'啟示錄'}
]

old_testiment_book_list = [
    {'name': 'Genesis', 'chapters': 50, 'title': u'創世紀 Genesis', 'sk_title': u'創世紀', 'cu_title': u'創世記'},
    {'name': 'Exodus', 'chapters': 40, 'title': u'出谷紀 Exodus', 'sk_title': u'出谷紀', 'cu_title': u'出埃及記'},
    {'name': 'Leviticus', 'chapters': 27, 'title': u'肋未紀 Levitcus', 'sk_title': u'肋未紀', 'cu_title': u'利未記'},
    {'name': 'Numbers', 'chapters': 36, 'title': u'戶籍紀 Numbers', 'sk_title': u'戶籍紀', 'cu_title': u'民數記'},
    {'name': 'Deuteronomy', 'chapters': 34, 'title': u'申命紀 Deuteronomy', 'sk_title': u'申命紀', 'cu_title': u'申命記'},
    {'name': 'Joshua', 'chapters': 24, 'title': u'若蘇厄書 Joshua', 'sk_title': u'若蘇厄書', 'cu_title': u'約書亞記'},
    {'name': 'Judges', 'chapters': 21, 'title': u'民長紀 Judges', 'sk_title': u'民長紀', 'cu_title': u'士師記'},
    {'name': 'Ruth', 'chapters': 4, 'title': u'盧德紀 Ruth', 'sk_title': u'盧德紀', 'cu_title': u'路得記'},
    {'name': '1_Samuel', 'chapters': 31, 'title': u'撒慕爾紀上 1 Samuel', 'sk_title': u'撒慕爾紀上', 'cu_title': u'撒母耳記上'},
    {'name': '2_Samuel', 'chapters': 24, 'title': u'撒慕爾紀下 2 Samuel', 'sk_title': u'撒慕爾紀下', 'cu_title': u'撒母耳記下'},
    {'name': '1_Kings', 'chapters': 22, 'title': u'列王紀上 1 Kings', 'sk_title': u'列王紀上', 'cu_title': u'列王紀上'},
    {'name': '2_Kings', 'chapters': 25, 'title': u'列王紀下 2 Kings', 'sk_title': u'列王紀下', 'cu_title': u'列王紀下'},
    {'name': '1_Chronicles', 'chapters': 29, 'title': u'編年紀上 1 Chronicles', 'sk_title': u'編年紀上', 'cu_title': u'歷代志上'},
    {'name': '2_Chronicles', 'chapters': 36, 'title': u'編年紀下 2 Chronicles', 'sk_title': u'編年紀下', 'cu_title': u'歷代志下'},
    {'name': 'Ezra', 'chapters': 10, 'title': u'厄斯德拉上 Ezra', 'sk_title': u'厄斯德拉上', 'cu_title': u'以斯拉記'},
    {'name': 'Nehemiah', 'chapters': 13, 'title': u'厄斯德拉下 Nehemiah', 'sk_title': u'厄斯德拉下', 'cu_title': u'尼希米記'},
    {'name': 'Esther', 'chapters': 10, 'title': u'艾斯德爾傳 Esther', 'sk_title': u'艾斯德爾傳', 'cu_title': u'以斯帖記'},
    {'name': 'Job', 'chapters': 42, 'title': u'約伯傳 Job', 'sk_title': u'約伯傳', 'cu_title': u'約伯記'},
    {'name': 'Psalms', 'chapters': 150, 'title': u'聖詠集 Psalms', 'sk_title': u'聖詠集', 'cu_title': u'詩篇'},
    {'name': 'Proverbs', 'chapters': 31, 'title': u'箴言 Proverbs', 'sk_title': u'箴言', 'cu_title': u'箴言'},
    {'name': 'Ecclesiastes', 'chapters': 12, 'title': u'訓道篇 Ecclesiastes', 'sk_title': u'訓道篇', 'cu_title': u'傳道書'},
    {'name': 'Song_of_Songs', 'chapters': 8, 'title': u'雅歌 Song of Songs', 'sk_title': u'雅歌', 'cu_title': u'雅歌'},
    {'name': 'Isaiah', 'chapters': 66, 'title': u'依撒意亞 Isaiah', 'sk_title': u'依撒意亞', 'cu_title': u'以賽亞書'},
    {'name': 'Jeremiah', 'chapters': 52, 'title': u'耶肋米亞 Jeremiah', 'sk_title': u'耶肋米亞', 'cu_title': u'耶利米書'},
    {'name': 'Lamentations', 'chapters': 5, 'title': u'哀歌 Lamentations', 'sk_title': u'哀歌', 'cu_title': u'耶利米哀歌'},
    {'name': 'Ezekiel', 'chapters': 48, 'title': u'厄則克耳 Ezekiel', 'sk_title': u'厄則克耳', 'cu_title': u'以西結書'},
    {'name': 'Daniel', 'chapters': 14, 'title': u'達尼爾 Daniel', 'sk_title': u'達尼爾', 'cu_title': u'但以理書'},
    {'name': 'Hosea', 'chapters': 14, 'title': u'歐瑟亞 Hosea', 'sk_title': u'歐瑟亞', 'cu_title': u'何西阿書'},
    {'name': 'Joel', 'chapters': 4, 'title': u'岳厄爾 Joel', 'sk_title': u'岳厄爾', 'cu_title': u'約珥書'},
    {'name': 'Amos', 'chapters': 9, 'title': u'亞毛斯 Amos', 'sk_title': u'亞毛斯', 'cu_title': u'阿摩司書'},
    {'name': 'Obadiah', 'chapters': 1, 'title': u'亞北底亞 Obadiah', 'sk_title': u'亞北底亞', 'cu_title': u'俄巴底亞書'},
    {'name': 'Jonah', 'chapters': 4, 'title': u'約納 Jonah', 'sk_title': u'約納', 'cu_title': u'約拿書'},
    {'name': 'Micah', 'chapters': 7, 'title': u'米該亞 Micah', 'sk_title': u'米該亞', 'cu_title': u'彌迦書'},
    {'name': 'Nahum', 'chapters': 3, 'title': u'納鴻 Nahum', 'sk_title': u'納鴻', 'cu_title': u'那鴻書'},
    {'name': 'Habakkuk', 'chapters': 3, 'title': u'哈巴谷 Habakkuk', 'sk_title': u'哈巴谷', 'cu_title': u'哈巴谷書'},
    {'name': 'Zephaniah', 'chapters': 3, 'title': u'索福尼亞 Zephaniah', 'sk_title': u'索福尼亞', 'cu_title': u'西番雅書'},
    {'name': 'Haggai', 'chapters': 2, 'title': u'哈蓋 Haggai', 'sk_title': u'哈蓋', 'cu_title': u'哈該書'},
    {'name': 'Zechariah', 'chapters': 14, 'title': u'匝加利亞 Zechariah', 'sk_title': u'匝加利亞', 'cu_title': u'撒迦利亞書'},
    {'name': 'Malachi', 'chapters': 3, 'title': u'瑪拉基亞 Malachi', 'sk_title': u'瑪拉基亞', 'cu_title': u'瑪拉基書'},
    # Extra 7 books
    {'name': 'Wisdom', 'chapters': 19, 'title': u'智慧篇 Wisdom', 'sk_title': u'智慧篇', 'cu_title': u'智慧篇'},
    {'name': 'Sirach', 'chapters': 51, 'title': u'德訓篇 Sirach', 'sk_title': u'德訓篇', 'cu_title': u'德訓篇'},
    {'name': '1_Maccabees', 'chapters': 16, 'title': u'瑪加伯上 1 Maccabees', 'sk_title': u'瑪加伯上', 'cu_title': u'瑪加伯上'},
    {'name': '2_Maccabees', 'chapters': 15, 'title': u'瑪加伯下 2 Maccabees', 'sk_title': u'瑪加伯下', 'cu_title': u'瑪加伯下'},
    {'name': 'Judith', 'chapters': 16, 'title': u'友弟德傳 Judith', 'sk_title': u'友弟德傳', 'cu_title': u'友弟德傳'},
    {'name': 'Baruch', 'chapters': 6, 'title': u'巴路克 Baruth', 'sk_title': u'巴路克', 'cu_title': u'巴路克'},
    {'name': 'Tobit', 'chapters': 14, 'title': u'多俾亞傳 Tobit', 'sk_title': u'多俾亞傳', 'cu_title': u'多俾亞傳'}
]
