# -*- coding: utf-8 -*-
test_list = [
    {'name': 'Zechariah', 'chapters': 14, 'title': u'匝加利亞 Zechariah'}
]

new_testiment_book_list = [
    {'name': 'Matthew', 'chapters': 28, 'title': u'瑪竇福音 Matthew'},
    {'name': 'Mark', 'chapters': 16, 'title': u'馬爾谷福音 Mark'},
    {'name': 'Luke', 'chapters': 24, 'title': u'路加福音 Luke'},
    {'name': 'John', 'chapters': 21, 'title': u'若望福音 John'},
    {'name': 'Acts', 'chapters': 28, 'title': u'宗徒大事錄 Acts'},
    {'name': 'Romans', 'chapters': 16, 'title': u'羅馬書 Roman'},
    {'name': '1_Corinthians', 'chapters': 16, 'title': u'格林多前書 1 Corinthians'},
    {'name': '2_Corinthians', 'chapters': 13, 'title': u'格林多後書 2 Corinthians'},
    {'name': 'Galatians', 'chapters': 6, 'title': u'迦拉達書 Galatians'},
    {'name': 'Ephesians', 'chapters': 6, 'title': u'厄弗所書 Ephesians'},
    {'name': 'Philippians', 'chapters': 4, 'title': u'斐理伯書 Philippians'},
    {'name': 'Colossians', 'chapters': 4, 'title': u'哥羅森書 Colossians'},
    {'name': '1_Thessalonians', 'chapters': 5, 'title': u'得撒洛尼前書 1 Thessalonians'},
    {'name': '2_Thessalonians', 'chapters': 3, 'title': u'得撒洛尼後書 2 Thessalonians'},
    {'name': '1_Timothy', 'chapters': 6, 'title': u'弟茂德前書 1Timothy'},
    {'name': '2_Timothy', 'chapters': 4, 'title': u'弟茂德後書 2Timothy'},
    {'name': 'Titus', 'chapters': 2, 'title': u'弟鐸書 Titus'},
    {'name': 'Philemon', 'chapters': 1, 'title': u'費肋孟書 Philemon'},
    {'name': 'Hebrews', 'chapters': 13, 'title': u'希伯來書 Hebrews'},
    {'name': 'James', 'chapters': 5, 'title': u'雅各伯書 James'},
    {'name': '1_Peter', 'chapters': 5, 'title': u'伯多祿前書 1 Peter'},
    {'name': '2_Peter', 'chapters': 3, 'title': u'伯多祿後書 2 Peter'},
    {'name': '1_John', 'chapters': 5, 'title': u'若望一書 1 John'},
    {'name': '2_John', 'chapters': 1, 'title': u'若望二書 2 John'},
    {'name': '3_John', 'chapters': 1, 'title': u'若望三書 3 John'},
    {'name': 'Jude', 'chapters': 1, 'title': u'猶達書 Jude'},
    {'name': 'Revelation', 'chapters': 22, 'title': u'若望默示錄  Revelation'}
]

old_testiment_book_list = [
    {'name': 'Genesis', 'chapters': 50, 'title': u'創世紀 Genesis'},
    {'name': 'Exodus', 'chapters': 40, 'title': u'出谷紀 Exodus'},
    {'name': 'Leviticus', 'chapters': 27, 'title': u'肋未紀 Levitcus'},
    {'name': 'Numbers', 'chapters': 36, 'title': u'戶籍紀 Number'},
    {'name': 'Deuteronomy', 'chapters': 34, 'title': u'申命紀 Deuteronomy'},
    {'name': 'Joshua', 'chapters': 24, 'title': u'若蘇厄書 Joshua'},
    {'name': 'Judges', 'chapters': 21, 'title': u'民長紀 Judges'},
    {'name': 'Ruth', 'chapters': 4, 'title': u'盧德紀 Ruth'},
    {'name': '1_Samuel', 'chapters': 31, 'title': u'撒慕爾紀上 1 Samuel'},
    {'name': '2_Samuel', 'chapters': 24, 'title': u'撒慕爾記下 2 Samuel'},
    {'name': '1_Kings', 'chapters': 22, 'title': u'列王紀上 1 Kings'},
    {'name': '2_Kings', 'chapters': 25, 'title': u'列王紀下 2 Kings'},
    {'name': '1_Chronicles', 'chapters': 29, 'title': u'編年紀上 1 Chronicles'},
    {'name': '2_Chronicles', 'chapters': 36, 'title': u'編年記下 2 Chronicles'},
    {'name': 'Ezra', 'chapters': 10, 'title': u'厄斯德拉上 Ezra'},
    {'name': 'Nehemiah', 'chapters': 13, 'title': u'厄斯德拉下 Nehemiah'},
    {'name': 'Esther', 'chapters': 10, 'title': u'艾斯德爾傳 Esther'},
    {'name': 'Job', 'chapters': 42, 'title': u'約伯傳 Job'},
    {'name': 'Psalms', 'chapters': 150, 'title': u'聖詠集 Psalms'},
    {'name': 'Proverbs', 'chapters': 31, 'title': u'箴言 Proverbs'},
    {'name': 'Ecclesiastes', 'chapters': 12, 'title': u'訓道篇 Ecclesiastes'},
    {'name': 'Song_of_Songs', 'chapters': 8, 'title': u'雅歌 Song of Songs'},
    {'name': 'Isaiah', 'chapters': 66, 'title': u'依撒意亞 Isaiah'},
    {'name': 'Jeremiah', 'chapters': 52, 'title': u'耶肋米亞 Jeremiah'},
    {'name': 'Lamentations', 'chapters': 5, 'title': u'哀歌 Lamentations'},
    {'name': 'Ezekiel', 'chapters': 48, 'title': u'厄則克爾 Ezekiel'},
    {'name': 'Daniel', 'chapters': 14, 'title': u'達尼爾 Daniel'},
    {'name': 'Hosea', 'chapters': 14, 'title': u'甌瑟亞 Hosea'},
    {'name': 'Joel', 'chapters': 4, 'title': u'岳厄爾 Joel'},
    {'name': 'Amos', 'chapters': 9, 'title': u'亞毛斯 Amos'},
    {'name': 'Obadiah', 'chapters': 1, 'title': u'亞北底亞 Obadiah'},
    {'name': 'Jonah', 'chapters': 4, 'title': u'約納 Jonah'},
    {'name': 'Micah', 'chapters': 7, 'title': u'米該亞 Micah'},
    {'name': 'Nahum', 'chapters': 3, 'title': u'納鴻 Nahum'},
    {'name': 'Habakkuk', 'chapters': 3, 'title': u'哈巴谷 Habakkuk'},
    {'name': 'Zephaniah', 'chapters': 3, 'title': u'索福尼亞 Zephaniah'},
    {'name': 'Haggai', 'chapters': 2, 'title': u'哈蓋 Haggai'},
    {'name': 'Zechariah', 'chapters': 14, 'title': u'匝加利亞 Zechariah'},
    {'name': 'Malachi', 'chapters': 3, 'title': u'瑪拉基亞 Malachi'},
    # Extra 7 books
    {'name': 'Wisdom', 'chapters': 19, 'title': u'智慧篇 Wisdom'},
    {'name': 'Sirach', 'chapters': 51, 'title': u'德訓篇 Sirach'},
    {'name': '1_Maccabees', 'chapters': 16, 'title': u'瑪加伯上 1 Maccabees'},
    {'name': '2_Maccabees', 'chapters': 15, 'title': u'瑪加伯下 2 Maccabees'},
    {'name': 'Judith', 'chapters': 16, 'title': u'友弟德傳 Judith'},
    {'name': 'Baruch', 'chapters': 6, 'title': u'巴路克 Baruth'},
    {'name': 'Tobit', 'chapters': 14, 'title': u'多俾亞傳 Tobit'}
]
